[build]
  base = "."
  command = "cd apps/web && rm -rf node_modules && npm install && npm run build"
  publish = "apps/web/dist"

[build.environment]
  NODE_VERSION = "20"
  VITE_API_BASE_URL = "https://your-railway-app.railway.app/api"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200