[build]
  base = "."
  command = "npm install && npm run build"
  publish = "apps/web/dist"

[build.environment]
  NODE_VERSION = "20"
  VITE_API_BASE_URL = "https://your-railway-app.railway.app/api"
  NPM_FLAGS = "--production=false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200