[build]
  base = "."
  command = "cd apps/web && npm ci && npm run build"
  publish = "apps/web/dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200