[build]
  base = "."
  command = "cd apps/web && rm -rf node_modules package-lock.json && npm install && npm run build"
  publish = "apps/web/dist"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200