services:
  - type: web
    name: barber-api
    env: node
    plan: starter
    buildCommand: cd apps/api && npm ci && npm run build
    startCommand: cd apps/api && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: barber-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
    healthCheckPath: /api/health

databases:
  - name: barber-db
    plan: starter
    databaseName: barber_booking
    user: barber_user
